baseURL: ""
languageCode: en-us
title: 18F Guides and Methods
theme: guides
languages:
  en:
    contentDir: content/en
    languageName: English
    title: 18F Guides and Methods
    weight: 2
  fr:
    contentDir: content/fr
    languageName: Français
    title: Guides et méthodes 18F
    weight: 1
  es:
    contentDir: content/es
    languageName: Español
    title: Guías y Métodos 18F
    weight: 3
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.4
Params:
  shortTitle: Guides
