baseURL = ''
languageCode = 'en-us'
title = '18F Guides and Methods'
theme = "guides"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    title = '18F Guides and Methods'
    weight = 2
  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    title = 'Guides et méthodes 18F'
    weight = 1
