baseURL: ""
languageCode: en-us
title: 18F Guides and Methods
theme: guides
languages:
  en:
    contentDir: content/en
    languageName: English
    title: 18F Guides and Methods
    weight: 1
  es:
    contentDir: content/es
    languageName: Español
    title: Guías y Métodos 18F
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.4
Params:
  shortTitle: Sections
  uswdsURL: https://designsystem.digital.gov/
