baseURL: ""
languageCode: en-us
title: 18F Guides and Methods
theme: guides
languages:
  en:
    contentDir: content/en
    languageName: English
    title: 18F Guides and Methods
    weight: 1
  es:
    contentDir: content/es
    languageName: Español
    title: Guías y Métodos 18F
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.4
sectionPagesMenu: sidenav
Params:
  shortTitle: Sections
  uswdsURL: https://designsystem.digital.gov/
  # Google Analytics & DAP tracking code for handbook
  google_analytics_ua: UA-48605964-19
  dap_agency: GSA
  dap_subagency: 18F,TTS
  # Add search site handle to enable search
  search_site_handle:
  site_email: 18F@gsa.gov
  agency: U.S. General Services Administration
  agency_acronym: GSA
  agency_logo: /assets/img/gsa-logo-blue.svg
  agency_url: https://www.gsa.gov
  agency_about_url: https://www.gsa.gov/about
  org_primary: Technology Transformation Services
  org_primary_acronym: TTS
  org_primary_url: https://www.gsa.gov/tts/
  org_primary_email: tts-info@gsa.gov
  org_primary_about: https://www.gsa.gov/tts/
  org_primary_bio: "As part of GSA’s Technology Transformation Services (TTS), we apply modern methodologies and technologies to improve the public’s experience with government. We help agencies make their services more accessible, efficient, and effective with modern applications, platforms, processes, personnel, and software solutions."
  org_secondary: 18F
  org_secondary_acronym: 18F
  org_secondary_logo: 18f-logo-blue.svg
  org_secondary_url: https://18f.gsa.gov
  org_secondary_email: 18F@gsa.gov
  org_secondary_about: https://18f.gsa.gov/about/
  org_secondary_bio: "TTS Solutions is a portfolio of products and services that help agencies improve delivery of information and services to the public."
  foia_request_url: "https://www.gsa.gov/reference/freedom-of-information-act-foia"
  fraud_waste_abuse_url: "https://www.gsaig.gov/"
  no_fear_act_url: "https://www.gsa.gov/about-us/organization/office-of-civil-rights/notification-and-federal-employee-antidiscrimination-and-retaliation-act-of-2002"
  budget_performance_url: "https://www.gsa.gov/reference/reports/budget-performance"
  accessibility_url: "https://www.gsa.gov/website-information/accessibility-aids"
  usagov_contact_url: "https://www.usa.gov/contact"
  privacy_policy_url: "https://www.gsa.gov/website-information/website-policies"
