name: a11y

on: [push]

jobs:
  pa11y:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Set up pa11y
        run: npm install

      - name: Run pa11y-ci on homepage
        run: npm run pa11y-ci:homepage
