name: a11y

on: [push]

jobs:
  pa11y:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'

      - name: Run Hugo server
        run: hugo server

      - name: Run pa11y-ci
        run: pa11y-ci --sitemap http://localhost:1313/sitemap.xml
