name: a11y

on: [push]

jobs:
  pa11y:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Set up pa11y
        run: npm install

      -
        run: curl -vvvv https://federalist-1d60e1c6-edfd-4ed3-b30a-e8a2a15b5cae.sites.pages.cloud.gov/preview/18f/guides-and-methods-hugo/jlallen/action-test/index.html

      - name: Run pa11y-ci on homepage
        run: npm run pa11y-ci:homepage

      - name: Run pa11y-ci on sitemap
        run: npm run pa11y-ci:sitemap
