name: a11y

on: [push]

jobs:
  pa11y:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Set up pa11y
        run: npm install

      - name: Build the site
        run: hugo

      - name: Run a server
        uses: Eun/http-server-action@v1
        with:
          directory: ./public
          port: 1313

      -
        run: curl -vvvv http://http://127.0.0.1:1313/index.html

      - name: Run pa11y-ci on homepage
        run: npm run pa11y-ci:homepage

      - name: Run pa11y-ci on sitemap
        run: npm run pa11y-ci:sitemap
